
project:
  type: website
  output-dir: docs
  
website:
  title: "Javier Enrique Aguilar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Presentations.qmd
      - About.qmd
      - text: Presentations
        href: Presentations.qmd
      - text: About
        href: About.qmd
    right: 
      - icon: envelope
        href: "mailto:javier.aguilar@cimat.mx"
      - icon: "github"
        href: https://github.com/jear2412
      - icon: "twitter"
        href: https://twitter.com/jear2412
  open-graph: true


format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

