
project:
  type: website
  output-dir: docs
  
website:
  title: "Javier Enrique Aguilar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Presentations
        href: Presentations.qmd
    right:
      - icon: github
        href: https://github.com/
        aria-label: GitHub
  open-graph: true
  

format:
   html:
    mainfont: arial
    css: styles.css
    toc: true

editor: visual


