
project:
  type: website
  output-dir: _site

publish:
  method: gh-pages
  
  #resources: 
   # - "talks/pdf/**"
    #- "teaching/**"
  
website:
  title: "J.E. Aguilar"
  #image: graphics/javier-aguilar-small.jpeg
  search: 
    location: navbar
    type: textbox
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: "Home"
      - text: "Publications"
        href: publications/index.qmd
      - text: "Events"
        href: talks/index.qmd
      - text: "Teaching" 
        href: teaching/index.qmd
      #- text: "Other" 
      #  href: teaching/index.qmd
     
    tools:
      - icon: envelope-fill
        href: "mailto:javier.aguilarr@icloud.com"
      - icon: github
        href: https://github.com/jear2412
  page-footer: 
      left: "copyright: 2025, Javier Enrique Aguilar. Thank you for visiting :)" 
      right: 
          - icon: envelope-fill
            href: mailto:javier.aguilarr@icloud.com
          - icon: github
            href: https://github.com/jear2412

  open-graph: true
  

format:
   html:
    #mainfont: arial
    theme: flatly
    css: styles.css
    #toc: true

#editor: visual


