---
title: Scientific Events
excerpt: "Talks, workshops, and collaborations in which I have participated."
page-layout: full
---

<details open>
<summary>**Upcoming**</summary>


-   [Nordstat 2026: 30th Nordic Conference in Mathematical Statistics](https://www.helsinki.fi/en/conferences/nordstat-2026), Helsinki, Finland – *Contributed Talk:* $R^2$ *Priors for Grouped Variance Decomposition in High-Dimensional Regression*
-   [StanCon 2026](https://www.stancon2026.org/registration/), Uppsala, Sweden – *Contributed Talk:* *Intuitive $R^2$-Based Prior Specification for High-Dimensional Models*
-   [ISBA World Meeting 2026](https://isba2026.github.io), Nagoya, Japan – *Contributed Talk:* $R^2$ *Priors for Grouped Variance Decomposition in High-Dimensional Regression*


</details>

------------------------------------------------------------------------


<details open>
<summary>**Talks & Conferences**</summary>


A selection of talks and conferences in which I have participated.

### 2025

-   [7th Joint Statistical Meeting of the Deutsche Arbeitsgemeinschaft Statistik (DAGStat 2025)](https://dagstat2025.de/#), Berlin, Germany – *Contributed Talk:* *Generalized Decomposition Priors on* $R^2$
-   [German Probability and Statistics Days (GPSD 2025)](https://www.gpsd-2025.de/), Dresden, Germany – *Contributed Talk:* *Dependency-Aware Shrinkage Priors*
-   [Summer School on Advanced Bayesian Methods](https://quetelet.be/summerschool/), Leuven, Belgium – *Participant*

### 2024

-   [International Conference on Statistics and Data Science (ICSDS 2024)](https://sites.google.com/view/ims-icsds2024/), Nice, France – *Contributed Talk:* *Generalized Decomposition Priors on* $R^2$
-   [Bayesian Methods for the Social Sciences II](https://bayesforshs2.sciencesconf.org), Amsterdam, Netherlands – *Poster:* *Generalized Decomposition Priors on* $R^2$
-   [ISBA World Meeting 2024](https://www.unive.it/web/en/2208/home), Venice, Italy – *Poster:* *Generalized Decomposition Priors on* $R^2$ (Accepted, not attended)
-   [Bernoulli–IMS 11th World Congress in Probability and Statistics 2024](https://www.bernoulli-ims-worldcongress2024.org), Bochum, Germany – *Contributed Talk:* *Generalized Decomposition Priors on* $R^2$ (Accepted, not attended)
-   [Visiting Scholar, Department of Computer Science, Aalto University](https://www.aalto.fi/en/department-of-computer-science), Helsinki, Finland – Project: *Grouped* $R^2$ Decomposition Priors (with [Aki Vehtari](https://users.aalto.fi/~ave/) and [David Kohns](https://davkoh.github.io))

### 2023

-   [International Conference on Multilevel Analysis 2023](https://multilevel.fss.uu.nl), Utrecht, Netherlands – *Contributed Talk:* *Intuitive Joint Priors for Bayesian Multilevel Models*
-   [NordStat 2023](https://nordstat2023.org), Gothenburg, Sweden – *Contributed Talk:* *Intuitive Joint Priors for Bayesian Multilevel Models*
-   [BayesComp 2023](https://bayescomp2023.com/home), Levi, Finland – *Poster:* *Intuitive Joint Priors for Bayesian Multilevel Models*
-   German Probability and Statistics Days (GPSD 2023), Essen, Germany – *Contributed Talk:* *Intuitive Joint Priors for Bayesian Multilevel Models*

### 2022

-   [International Conference on Statistics and Data Science (ICSDS 2022)](https://sites.google.com/view/icsds2022), Florence, Italy – *Invited Talk:* *Intuitive Joint Priors for Bayesian Multilevel Models(Recipient of the [IMS Student Travel Award](https://imstat.org/2022/12/06/2022-icsds-travel-award-recipients/))*

-  [Computational methods for unifying multiple statistical analyses (Fusion)](https://conferences.cirm-math.fr/2635.html), CIRM, Marseille, France. *Participant*

</details>

------------------------------------------------------------------------


<details open>
<summary>**Workshops & Tutorials**</summary>

A selection of workshops and tutorials I have organized and taught.



### 2026

-   University of Bern, Bern, Switzerland – *Workshop: Bayesian Structural Equation Modeling with `blavaan`* (Instructor)


### 2025

-   [Conference of the DGPs Methods and Evaluation Section 2025](http://methods-berlin.com/en/fgme2025/), Berlin, Germany – *Workshop: Bayesian Data Analysis* (Instructor)
-   [Alumni-Verein Dortmunder Statistikerinnen und Statistiker e.V. and Faculty of Statistics](http://www.statistik.tu-dortmund.de/alumni-verein.html), Dortmund, Germany – *Bayesian Data Analysis Workshop with `brms`* (Instructor with [Luna Fazio](https://lunafazio.github.io))
-   [València International Bayesian Analysis Summer School (VIBASS 8)](http://vabar.es/events/vibass8/), València, Spain – *Workshop: Bayesian Data Analysis* (Instructor)
-   [7th Joint Statistical Meeting of the Deutsche Arbeitsgemeinschaft Statistik (DAGStat 2025)](https://dagstat2025.de/#), Humboldt University of Berlin, Germany – *Tutorial: Bayesian Data Analysis Workshop* (Instructor with [Luna Fazio](https://lunafazio.github.io))

### 2024

-   Freie Universität Berlin, Berlin, Germany – *Workshop: Bayesian Data Analysis Workshop with `brms`* (Instructor)
-   Charité – Universitätsmedizin Berlin, Berlin, Germany – *Workshop: Bayesian Data Analysis Workshop with `brms`* (Instructor with [Maximilian Scholz](https://scholzmx.com))

</details>


