---
title: Scientific Publications
excerpt: "Peer-reviewed publications and preprints."
toc-location: right
page-layout: full
---

## Accepted

### 2025

- **Aguilar, J. E.**, & Bürkner, P.-C. (2025). [Generalized decomposition priors on $R^2$](https://projecteuclid.org/journals/bayesian-analysis/advance-publication/Generalized-Decomposition-Priors-on-R2/10.1214/25-BA1524.full). *Bayesian Analysis*. Open access on [arXiv](https://arxiv.org/abs/2401.10180). doi:[10.1214/25-BA1524](https://doi.org/10.1214/25-BA1524)

- Reiser, P., **Aguilar, J. E.**, Guthke, A., & Bürkner, P.-C. (2025). [Uncertainty quantification and propagation in surrogate-based Bayesian inference](https://link.springer.com/article/10.1007/s11222-025-10597-8). *Statistics and Computing*. Open access on [arXiv](https://arxiv.org/abs/2312.05153). doi:[10.1007/s11222-025-10597-8](https://doi.org/10.1007/s11222-025-10597-8)

- Matabuena, M., Ghosal, R., **Aguilar, J. E.**, Wagner, R., Merino, C. F., Castro, J. S., Zipunnikov, V., Onnela, J. P., & Gude, F. (2025). [Glucodensity functional profiles outperform traditional continuous glucose monitoring metrics](https://www.nature.com/articles/s41598-025-18119-2#Sec15). *Nature Scientific Reports*. doi:[10.1038/s41598-025-18119-2](https://doi.org/10.1038/s41598-025-18119-2)

### 2023

- **Aguilar, J. E.**, & Bürkner, P.-C. (2023). [Intuitive joint priors for Bayesian linear multilevel models: the R2D2M2 prior](https://doi.org/10.1214/23-EJS2136). *Electronic Journal of Statistics*. Open access on [arXiv](https://arxiv.org/abs/2208.07132). doi:[10.1214/23-EJS2136](https://doi.org/10.1214/23-EJS2136)

---

## In review

- Mukherjee, S., **Aguilar, J. E.**, Zago M., Classen M., & Bürkner, P.-C. (2025). [Latent variable estimation with composite Hilbert space Gaussian processes](https://arxiv.org/abs/2510.25371). *arXiv preprint*.


- **Aguilar, J. E.**, Kohns, D., Vehtari, A., & Bürkner, P.-C. (2025). [$R^2$ priors for grouped variance decomposition in high-dimensional regression](https://arxiv.org/abs/2507.11833). *arXiv preprint*.

- Fazio, L., Scholz, M., **Aguilar, J. E.**, & Bürkner, P.-C. (2025). [Primed priors for simulation-based validation of Bayesian models](https://arxiv.org/abs/2408.06504). *arXiv preprint*.

- **Aguilar, J. E.**, & Bürkner, P.-C. (2025). [Dependency-aware shrinkage priors for high-dimensional regression](https://arxiv.org/abs/2505.10715). *arXiv preprint*.